/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'starocker' at '16/07/07 23:24' with Gradle 2.13
 *
 * @author starocker, @date 16/07/07 23:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
